/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CaptureRouteImport } from './routes/capture'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as MeasurementsRouteImport } from './routes/measurements'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as VrRouteImport } from './routes/vr'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as FilesSplatRouteImport } from './routes/files/$'
import { Route as ApiImagesSplatRouteImport } from './routes/api/images/$'
import { Route as ApiPanoramasSplatRouteImport } from './routes/api/panoramas/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptureRoute = CaptureRouteImport.update({
  id: '/capture',
  path: '/capture',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const MeasurementsRoute = MeasurementsRouteImport.update({
  id: '/measurements',
  path: '/measurements',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const VrRoute = VrRouteImport.update({
  id: '/vr',
  path: '/vr',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesSplatRoute = FilesSplatRouteImport.update({
  id: '/files/$',
  path: '/files/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImagesSplatRoute = ApiImagesSplatRouteImport.update({
  id: '/api/images/$',
  path: '/api/images/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPanoramasSplatRoute = ApiPanoramasSplatRouteImport.update({
  id: '/api/panoramas/$',
  path: '/api/panoramas/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/capture': typeof CaptureRoute
  '/contact': typeof ContactRoute
  '/measurements': typeof MeasurementsRoute
  '/plan': typeof PlanRoute
  '/studio': typeof StudioRoute
  '/upload': typeof UploadRoute
  '/vr': typeof VrRoute
  '/api/health': typeof ApiHealthRoute
  '/api/upload': typeof ApiUploadRoute
  '/files/$': typeof FilesSplatRoute
  '/api/images/$': typeof ApiImagesSplatRoute
  '/api/panoramas/$': typeof ApiPanoramasSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/capture': typeof CaptureRoute
  '/contact': typeof ContactRoute
  '/measurements': typeof MeasurementsRoute
  '/plan': typeof PlanRoute
  '/studio': typeof StudioRoute
  '/upload': typeof UploadRoute
  '/vr': typeof VrRoute
  '/api/health': typeof ApiHealthRoute
  '/api/upload': typeof ApiUploadRoute
  '/files/$': typeof FilesSplatRoute
  '/api/images/$': typeof ApiImagesSplatRoute
  '/api/panoramas/$': typeof ApiPanoramasSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/capture': typeof CaptureRoute
  '/contact': typeof ContactRoute
  '/measurements': typeof MeasurementsRoute
  '/plan': typeof PlanRoute
  '/studio': typeof StudioRoute
  '/upload': typeof UploadRoute
  '/vr': typeof VrRoute
  '/api/health': typeof ApiHealthRoute
  '/api/upload': typeof ApiUploadRoute
  '/files/$': typeof FilesSplatRoute
  '/api/images/$': typeof ApiImagesSplatRoute
  '/api/panoramas/$': typeof ApiPanoramasSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/capture'
    | '/contact'
    | '/measurements'
    | '/plan'
    | '/studio'
    | '/upload'
    | '/vr'
    | '/api/health'
    | '/api/upload'
    | '/files/$'
    | '/api/images/$'
    | '/api/panoramas/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/capture'
    | '/contact'
    | '/measurements'
    | '/plan'
    | '/studio'
    | '/upload'
    | '/vr'
    | '/api/health'
    | '/api/upload'
    | '/files/$'
    | '/api/images/$'
    | '/api/panoramas/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/capture'
    | '/contact'
    | '/measurements'
    | '/plan'
    | '/studio'
    | '/upload'
    | '/vr'
    | '/api/health'
    | '/api/upload'
    | '/files/$'
    | '/api/images/$'
    | '/api/panoramas/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  CaptureRoute: typeof CaptureRoute
  ContactRoute: typeof ContactRoute
  MeasurementsRoute: typeof MeasurementsRoute
  PlanRoute: typeof PlanRoute
  StudioRoute: typeof StudioRoute
  UploadRoute: typeof UploadRoute
  VrRoute: typeof VrRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiUploadRoute: typeof ApiUploadRoute
  FilesSplatRoute: typeof FilesSplatRoute
  ApiImagesSplatRoute: typeof ApiImagesSplatRoute
  ApiPanoramasSplatRoute: typeof ApiPanoramasSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capture': {
      id: '/capture'
      path: '/capture'
      fullPath: '/capture'
      preLoaderRoute: typeof CaptureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/measurements': {
      id: '/measurements'
      path: '/measurements'
      fullPath: '/measurements'
      preLoaderRoute: typeof MeasurementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vr': {
      id: '/vr'
      path: '/vr'
      fullPath: '/vr'
      preLoaderRoute: typeof VrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files/$': {
      id: '/files/$'
      path: '/files/$'
      fullPath: '/files/$'
      preLoaderRoute: typeof FilesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/images/$': {
      id: '/api/images/$'
      path: '/api/images/$'
      fullPath: '/api/images/$'
      preLoaderRoute: typeof ApiImagesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/panoramas/$': {
      id: '/api/panoramas/$'
      path: '/api/panoramas/$'
      fullPath: '/api/panoramas/$'
      preLoaderRoute: typeof ApiPanoramasSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  CaptureRoute: CaptureRoute,
  ContactRoute: ContactRoute,
  MeasurementsRoute: MeasurementsRoute,
  PlanRoute: PlanRoute,
  StudioRoute: StudioRoute,
  UploadRoute: UploadRoute,
  VrRoute: VrRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiUploadRoute: ApiUploadRoute,
  FilesSplatRoute: FilesSplatRoute,
  ApiImagesSplatRoute: ApiImagesSplatRoute,
  ApiPanoramasSplatRoute: ApiPanoramasSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
